### ISSUE TITLE
Standup bugs

### ISSUE THREAD

**Issue by dofu** [sofetch/slack-standup-bot#36]
The app works fine when I tested it, twice.
When I tried using it in a live environment, it tends to freeze.

The 'complete with report link' message does not appear when we have completed our report.
or
when a user completes his 3rd question, it does not proceed to the next person
or
when i type -n/a: @user , there is no respond. 

and I could not delete today's entry to retry again.

Is there anything I could do? =(

**Comment by santiagodoldan** [comment]
@dofu are you using heroku?

**Comment by dofu** [comment]
yes =)

**Comment by santiagodoldan** [comment]
yep, we are also having the same issue because heroku kills the standup client sometimes, I pushed some new changes that could improve the experience using heroku, pull the latest changes in master and let me know if you still have the same issue.

you would need to configure an smtp server (I updated the README) or visit /users and deactivate all the checkboxes there, the standupbot now includes a new feature that sends a report to the email of each user after the standup finishes.

**Comment by santiagodoldan** [comment]
@dofu having latest changes seems to fix the heroku bugs, we didn't have those problems neither yesterday nor today.

Please update your heroku app and let me know if that fixes the errors you were having, so I can close this issue.

Thanks

**Comment by santiagodoldan** [comment]
going to close this one, please re-open if you still have the same issues
