### ISSUE TITLE
Channel state fails to idle

### ISSUE THREAD

**Issue by dhoffmann** [sofetch/slack-standup-bot#63]
Ran into an issue today where a few channels were still considered _active_ from the day before. This leads to no response from the bot and no traceable error.

I'll look into it more, soon.

**Comment by santiagodoldan** [comment]
Yes, we had the same issue last week, I'm not sure how that happened though.

Let me know if you are able to reproduce it, I can help you to fix it.

Thanks

**Comment by santiagodoldan** [comment]
Maybe this is because when something wrong happen within a "realtime.on" block, that exception is not being caught by this rescue https://github.com/sofetch/slack-standup-bot/blob/master/lib/standupbot/client.rb#L71.

We can create a method for that.

```ruby
def rescue_exceptions
  begin
    yield
  rescue StandardError
    channel.stop! if channel.try(:active?)
  end
end
```

Another place that we are not changing the state back to idle is within the AutoSkip class, if something wrong happens there the channel won't change back to idle.

Cheers
