### ISSUE TITLE
New user not included in standup

### ISSUE THREAD

**Issue by Potherca** [sofetch/slack-standup-bot#66]
We have the bot running in a separate channel dedicated to our standups. After testing the bot with a co-worker I invited another user to that channel.

Now, when I start a standup, me and my co-worker get asked the standup questions but the newly invited colleague isn't.

The colleague does show up in the web interface (on the users page).

Is there something I need to do to make the bot include this colleague in the standup or is this a bug in the bot?

**Comment by santiagodoldan** [comment]
We had a similar issue but it was only because we invited a new user while we were doing a standup.

When you start a new standup session, all the new users are created in your database and they will might participate of the standup, I'm not sure why that user is not, I would need more information to figure out what's going on there. Could you check if that user have the "disabled" flag on? You can check that in the users list page.

Cheers

**Comment by Potherca** [comment]
It _looks_ like there was another standup already running. We didn't notice until re-installing the bot. Most likely that was messing with things.
