### ISSUE TITLE
Use Direct Messages for unobtrusive async standups?

### ISSUE THREAD

**Issue by kevinjalbert** [sofetch/slack-standup-bot#73]
I gave this a spin yesterday and it worked out quite well. My major feature request for this would be to have the bot's collection of member's answers done in a Direct Message. Two major benefits to this approach:
 1. The bot can effectively ask a question to _everyone_ at the same time. This removes _waiting_ for your turn.
 2. Less chatter in the Standup channel.

I saw that https://geekbot.io/ does this. I haven't tried it, but their approach seems to match what I'm describing.

I haven't looked into the source, and I have a feeling this is probably a large change (architecturally). I'm just curious if this is something that could be on a road map, and/or useful to others.

**Comment by eddively** [comment]
I just want to second this suggestion using DMs.

**Comment by timchilcott** [comment]
From our standpoint here at So Fetch we don't want to go down the route of purely asynchronous standups.

Here is an excert from a post I wrote.

_Asynchronous meetings are not standups. In theory, we did the meeting at the same time. But we didn’t, because the team could always pop in late and give their standup after everyone left. There was no such thing as ‘missing’ the meeting. We also had to monitor it, and sometimes remind people to give their standup. It was a waste of time. It also became hectic when everyone posted at random. Something had to give.

By definition, a daily standup is a synchronization meeting. The point of a standup is to get your team to synchronize their work, and to do it quickly. Standups makes you commit to your team that you’ll finish something, in real time. So completing your standup asynchronously removes that commitment.
Synchronous standups apply social pressure._

So what we did is build a hybrid approach into our paid product Standup Bot. [http://standupbot.com]

 Our hybrid approach works like this.

_Hybrid standups — Standup Bot takes a hybrid approach, melding synchronous and asynchronous standups. Synchronous standups come first, but we allow the stragglers a chance to complete their standup within 8 hours on the same day. Async teams get in sync._

**Comment by kevinjalbert** [comment]
@timchilcott that is an excellent response. In my situation we're still doing synchronous standups (i.e, always happens at the same time, and same time block). My original issue is simply referring to the delivery and receiving of status updates to the bot. _Looking back I guess it isn't a huge issue as the point is you can simply wait for the Bot to announce your turn and wait for the final report._ I was simply looking at how to make things faster.

I can foresee issues with someone not responding, and I guess there has to be some logic in place (i.e., ask for status updates 5 times with the timeout specified, if nothing then proceed). Also could be issues if you were apart of multiple standups.

An example scenario with a standup of 10~ people:

1. An admin initiates the standup (`/standup`)
2. Everyone involved in standup receives a DM asking for them to initiate their response (`-Yes`)
3. Everyone responds to standup questions (for simplicity we will assume everyone is present).
4. Bot response with standup is completed and proceeds to send report.

The main benefit of using DMs here is that the whole standup process is completed quicker.

**Comment by eddively** [comment]
Exactly.

I'd like everyone to be able to answer simultaneously through DM, and also this would reduce clutter in the channels.

**Comment by timchilcott** [comment]
There are other tools that allow this but I don't think we are going to go down that route here. Quick isn't what makes a standup most effective. We thin having a team sync up leads to more conversation and better results for standups.

**Comment by kevinjalbert** [comment]
Sounds like this feature request does not align with the project direction. Alternatives have been mentioned in this thread.

I will close this issue.
